/**
 * ODDKIN FOUNDRY - Starter Data & Foundational Constants
 * Six Primitive Materials & Deep Meaningful Processes
 */

import { Material, Process, Habitat } from '../types';

export const STARTER_MATERIALS: Material[] = [
  {
    id: 'mat_water',
    canonicalName: 'WATER',
    displayName: 'Water',
    description: 'Clear, fluid solvent that nurtures organic bonds and sustains life.',
    category: 'Elemental',
    subcategory: 'Primordial Solvent',
    stateOfMatter: 'liquid',
    properties: {
      organic: false,
      living: false,
      edible: true,
      metallic: false,
      mineral: false,
      liquid: true,
      gaseous: false,
      crystalline: false,
      synthetic: false,
      conductive: true,
      magnetic: false,
      flammable: false,
      toxic: false,
      fragile: false,
      elastic: false,
      porous: false,
    },
    temperatureClass: 'ambient',
    semanticTags: ['solvent', 'aquatic', 'clean', 'fluid', 'life_giving'],
    lineage: {
      parentIds: [],
      depth: 0,
      generation: 0,
      recipeDesc: 'Primordial source fluid'
    },
    rarity: 'COMMON',
    discoveredAt: 1700000000000,
    possibleProcessAffinities: ['FREEZE', 'HEAT', 'DISTILL', 'CONDENSE', 'SOAK', 'MIX'],
    lifePotential: 35,
    spriteDescriptor: {
      palette: ['#1e40af', '#3b82f6', '#93c5fd', '#e0f2fe'],
      baseShape: 'droplet',
      primaryColor: '#3b82f6',
      secondaryColor: '#1e40af',
      accentColor: '#93c5fd',
    },
    discoveryExplanation: 'Fundamental liquid found naturally across the world.',
  },
  {
    id: 'mat_stone',
    canonicalName: 'STONE',
    displayName: 'Stone',
    description: 'Dense, enduring silicate crust composed of compressed minerals.',
    category: 'Mineral',
    subcategory: 'Bedrock',
    stateOfMatter: 'solid',
    properties: {
      organic: false,
      living: false,
      edible: false,
      metallic: false,
      mineral: true,
      liquid: false,
      gaseous: false,
      crystalline: false,
      synthetic: false,
      conductive: false,
      magnetic: false,
      flammable: false,
      toxic: false,
      fragile: false,
      elastic: false,
      porous: false,
    },
    temperatureClass: 'ambient',
    semanticTags: ['dense', 'heavy', 'mineral', 'rigid', 'hard'],
    lineage: {
      parentIds: [],
      depth: 0,
      generation: 0,
      recipeDesc: 'Primordial solid crust'
    },
    rarity: 'COMMON',
    discoveredAt: 1700000000000,
    possibleProcessAffinities: ['CRUSH', 'HEAT', 'POLISH', 'CUT'],
    lifePotential: 5,
    spriteDescriptor: {
      palette: ['#374151', '#4b5563', '#9ca3af', '#d1d5db'],
      baseShape: 'rock',
      primaryColor: '#4b5563',
      secondaryColor: '#374151',
      accentColor: '#9ca3af',
    },
    discoveryExplanation: 'Foundational geological stone form.',
  },
  {
    id: 'mat_soil',
    canonicalName: 'SOIL',
    displayName: 'Soil',
    description: 'Dark loam rich in decayed organics, micro-nutrients and damp grit.',
    category: 'Mineral',
    subcategory: 'Fertile Earth',
    stateOfMatter: 'solid',
    properties: {
      organic: true,
      living: false,
      edible: false,
      metallic: false,
      mineral: true,
      liquid: false,
      gaseous: false,
      crystalline: false,
      synthetic: false,
      conductive: false,
      magnetic: false,
      flammable: false,
      toxic: false,
      fragile: true,
      elastic: false,
      porous: true,
    },
    temperatureClass: 'ambient',
    semanticTags: ['fertile', 'earth', 'ground', 'nutrients', 'substrate'],
    lineage: {
      parentIds: [],
      depth: 0,
      generation: 0,
      recipeDesc: 'Primordial fertile loam'
    },
    rarity: 'COMMON',
    discoveredAt: 1700000000000,
    possibleProcessAffinities: ['MIX', 'DRY', 'HEAT', 'GROW', 'INCUBATE'],
    lifePotential: 40,
    spriteDescriptor: {
      palette: ['#451a03', '#78350f', '#92400e', '#b45309'],
      baseShape: 'powder',
      primaryColor: '#78350f',
      secondaryColor: '#451a03',
      accentColor: '#b45309',
    },
    discoveryExplanation: 'Living loam awaiting catalyst interaction.',
  },
  {
    id: 'mat_plant',
    canonicalName: 'PLANT',
    displayName: 'Plant',
    description: 'Fibrous green photosynthetic flora brimming with active chloroplasts.',
    category: 'Organic',
    subcategory: 'Botanical',
    stateOfMatter: 'solid',
    properties: {
      organic: true,
      living: true,
      edible: true,
      metallic: false,
      mineral: false,
      liquid: false,
      gaseous: false,
      crystalline: false,
      synthetic: false,
      conductive: false,
      magnetic: false,
      flammable: true,
      toxic: false,
      fragile: true,
      elastic: true,
      porous: true,
    },
    temperatureClass: 'ambient',
    semanticTags: ['flora', 'green', 'photosynthetic', 'botanical', 'cellulose'],
    lineage: {
      parentIds: [],
      depth: 0,
      generation: 0,
      recipeDesc: 'Wild vegetative sprouts'
    },
    rarity: 'COMMON',
    discoveredAt: 1700000000000,
    possibleProcessAffinities: ['DRY', 'CRUSH', 'FERMENT', 'INCUBATE', 'HEAT'],
    lifePotential: 60,
    spriteDescriptor: {
      palette: ['#064e3b', '#047857', '#10b981', '#6ee7b7'],
      baseShape: 'flora',
      primaryColor: '#10b981',
      secondaryColor: '#047857',
      accentColor: '#6ee7b7',
    },
    discoveryExplanation: 'Living vegetative sprout loaded with potential.',
  },
  {
    id: 'mat_metal',
    canonicalName: 'METAL',
    displayName: 'Metal',
    description: 'Raw lustrous elemental iron ore with notable magnetic ductility.',
    category: 'Metallic',
    subcategory: 'Native Ore',
    stateOfMatter: 'solid',
    properties: {
      organic: false,
      living: false,
      edible: false,
      metallic: true,
      mineral: true,
      liquid: false,
      gaseous: false,
      crystalline: true,
      synthetic: false,
      conductive: true,
      magnetic: true,
      flammable: false,
      toxic: false,
      fragile: false,
      elastic: false,
      porous: false,
    },
    temperatureClass: 'ambient',
    semanticTags: ['conductive', 'ferrous', 'ore', 'rigid', 'metallic', 'ductile'],
    lineage: {
      parentIds: [],
      depth: 0,
      generation: 0,
      recipeDesc: 'Native metallic deposit'
    },
    rarity: 'COMMON',
    discoveredAt: 1700000000000,
    possibleProcessAffinities: ['HEAT', 'MAGNETIZE', 'CHARGE', 'POLISH', 'CRUSH'],
    lifePotential: 10,
    spriteDescriptor: {
      palette: ['#334155', '#475569', '#94a3b8', '#e2e8f0'],
      baseShape: 'ingot',
      primaryColor: '#64748b',
      secondaryColor: '#334155',
      accentColor: '#e2e8f0',
    },
    discoveryExplanation: 'Unrefined conductive metallic element.',
  },
  {
    id: 'mat_spark',
    canonicalName: 'SPARK',
    displayName: 'Spark',
    description: 'Fleeting burst of thermal and electrostatic plasma discharge.',
    category: 'Energy',
    subcategory: 'Discharge',
    stateOfMatter: 'plasma',
    properties: {
      organic: false,
      living: false,
      edible: false,
      metallic: false,
      mineral: false,
      liquid: false,
      gaseous: false,
      crystalline: false,
      synthetic: false,
      conductive: true,
      magnetic: false,
      flammable: true,
      toxic: false,
      fragile: true,
      elastic: false,
      porous: false,
    },
    temperatureClass: 'incandescent',
    semanticTags: ['plasma', 'fire', 'electric', 'energetic', 'kinetic', 'ignite'],
    lineage: {
      parentIds: [],
      depth: 0,
      generation: 0,
      recipeDesc: 'Spontaneous plasma arc'
    },
    rarity: 'COMMON',
    discoveredAt: 1700000000000,
    possibleProcessAffinities: ['CHARGE', 'HEAT', 'ILLUMINATE', 'CONDENSE'],
    lifePotential: 50,
    spriteDescriptor: {
      palette: ['#7c2d12', '#ea580c', '#fbbf24', '#fef08a'],
      baseShape: 'sparks',
      primaryColor: '#fbbf24',
      secondaryColor: '#ea580c',
      accentColor: '#fef08a',
      glow: true,
    },
    discoveryExplanation: 'Concentrated energetic discharge ready to catalyze matter.',
  }
];

export const ALL_PROCESSES: Process[] = [
  { id: 'FOSSILIZE', name: 'Fossilize', verb: 'preserves structure while replacing tissue with minerals', description: 'Compress ages into a moment: preserve patterns, bones and botanical forms in stone.', category: 'Temporal', symbol: '🦴', unlocked: true },
  { id: 'ENCHANT', name: 'Enchant', verb: 'binds a magical function to the material’s existing traits', description: 'Give ordinary matter a specific magical purpose rooted in what it already does.', category: 'Alchemical', symbol: '🪄', unlocked: true },
  { id: 'MINIATURIZE', name: 'Miniaturize', verb: 'shrinks while preserving characteristic structure', description: 'Discover pocket worlds, tiny mechanisms and miniature habitats.', category: 'Alchemical', symbol: '🔬', unlocked: true },
  { id: 'MOONLIGHT', name: 'Moonlight', verb: 'bathes in fictional lunar energy', description: 'Explore nocturnal forms, luminous pigments and moonlit materials.', category: 'Alchemical', symbol: '🌙', unlocked: true },

  {
    id: 'MIX',
    name: 'Mix',
    verb: 'blends and stirs',
    description: 'Combines two substances thoroughly into an integrated amalgam or suspension.',
    category: 'Mechanical',
    symbol: '🌀',
    unlocked: true,
  },
  {
    id: 'HEAT',
    name: 'Heat',
    verb: 'applies intense thermal energy to',
    description: 'Increases molecular energy, drives off volatiles, or melts crystalline bonds.',
    category: 'Thermal',
    symbol: '🔥',
    unlocked: true,
  },
  {
    id: 'DRY',
    name: 'Dry',
    verb: 'draws out moisture and evaporates humidity from',
    description: 'Desiccates damp or aqueous matter, concentrating solids.',
    category: 'Thermal',
    symbol: '☀️',
    unlocked: true,
  },
  {
    id: 'COOL',
    name: 'Cool',
    verb: 'lowers the temperature of',
    description: 'Reduces kinetic thermal excitement, steadying reactive materials.',
    category: 'Thermal',
    symbol: '❄️',
    unlocked: true,
  },
  {
    id: 'FREEZE',
    name: 'Freeze',
    verb: 'sub-cools into rigid crystalline frost',
    description: 'Drops temperature below the freezing threshold, locking fluids into lattice solids.',
    category: 'Thermal',
    symbol: '🧊',
    unlocked: true,
  },
  {
    id: 'CRUSH',
    name: 'Crush',
    verb: 'pulverizes with immense mechanical pressure',
    description: 'Grinds brittle solids down into fine particles or powder.',
    category: 'Mechanical',
    symbol: '🔨',
    unlocked: true,
  },
  {
    id: 'PRESS',
    name: 'Press',
    verb: 'applies uniform compressive force to',
    description: 'Compacts loose grains, squeezes out fluids, or stamps into plates.',
    category: 'Mechanical',
    symbol: '🧱',
    unlocked: true,
  },
  {
    id: 'SOAK',
    name: 'Soak',
    verb: 'submerges in fluid to saturate pores',
    description: 'Infuses a porous solid with ambient liquid medium.',
    category: 'Alchemical',
    symbol: '💧',
    unlocked: true,
  },
  // Gradually discovered / unlocked processes:
  {
    id: 'INCUBATE',
    name: 'Incubate',
    verb: 'gently warms in an insulated nutrient cradle',
    description: 'Maintains optimal bio-temperature to awaken latent living spores or cells.',
    category: 'Biological',
    symbol: '🥚',
    unlocked: true,
  },
  {
    id: 'FERMENT',
    name: 'Ferment',
    verb: 'encourages microbial digestive culture in',
    description: 'Converts complex carbohydrates and sugars via bacterial enzymes.',
    category: 'Biological',
    symbol: '🧪',
    unlocked: true,
  },
  {
    id: 'GROW',
    name: 'Grow',
    verb: 'cultivates cellular expansion through time',
    description: 'Allows biological tissue to replicate, sprout, and weave new structures.',
    category: 'Biological',
    symbol: '🌱',
    unlocked: true,
  },
  {
    id: 'CHARGE',
    name: 'Charge',
    verb: 'injects an intense electrostatic current into',
    description: 'Energizes conductible bonds with free electrons.',
    category: 'Electromagnetic',
    symbol: '⚡',
    unlocked: true,
  },
  {
    id: 'POLISH',
    name: 'Polish',
    verb: 'abrades and buffs surface asperities on',
    description: 'Removes micro-roughness to reveal internal luster or transparency.',
    category: 'Mechanical',
    symbol: '✨',
    unlocked: false,
  },
  {
    id: 'MAGNETIZE',
    name: 'Magnetize',
    verb: 'aligns ferromagnetic dipoles across',
    description: 'Induces a persistent electromagnetic pole.',
    category: 'Electromagnetic',
    symbol: '🧲',
    unlocked: false,
  },
  {
    id: 'DISTILL',
    name: 'Distill',
    verb: 'vaporizes and selectively re-condenses fractions of',
    description: 'Purifies volatile essences by separating thermal fractions.',
    category: 'Alchemical',
    symbol: '⚗️',
    unlocked: false,
  },
  {
    id: 'FILTER',
    name: 'Filter',
    verb: 'strains particulate matter through micro-mesh from',
    description: 'Separates insoluble sediment from clear fluid filtrate.',
    category: 'Mechanical',
    symbol: '☕',
    unlocked: false,
  },
  {
    id: 'CONDENSE',
    name: 'Condense',
    verb: 'compresses vapor into droplets through pressure',
    description: 'Transforms dispersed gases into concentrated liquids.',
    category: 'Alchemical',
    symbol: '🌫️',
    unlocked: false,
  },
  {
    id: 'DISSOLVE',
    name: 'Dissolve',
    verb: 'breaks ionic bonds to dissolve solute into',
    description: 'Breaks down a soluble solid into a homogenous solution.',
    category: 'Alchemical',
    symbol: '🫧',
    unlocked: false,
  },
  {
    id: 'AGE',
    name: 'Age',
    verb: 'allows temporal maturation across time upon',
    description: 'Simulates extended exposure to ambient pressure, oxidation, and decay.',
    category: 'Temporal',
    symbol: '⏳',
    unlocked: false,
  },
  {
    id: 'ILLUMINATE',
    name: 'Illuminate',
    verb: 'bathes in radiant photon bombardment',
    description: 'Stimulates light-reactive molecules and activates photobiology.',
    category: 'Electromagnetic',
    symbol: '💡',
    unlocked: false,
  },
  {
    id: 'DARKEN',
    name: 'Darken',
    verb: 'secludes in void shielding away from radiation',
    description: 'Stimulates subterranean, cave-adapted, or anaerobic reactions.',
    category: 'Temporal',
    symbol: '🌑',
    unlocked: false,
  },
  {
    id: 'CUT',
    name: 'Cut',
    verb: 'cleaves along cleavage planes',
    description: 'Slices fibrous or crystalline material into precision segments.',
    category: 'Mechanical',
    symbol: '✂️',
    unlocked: false,
  }
];

export const INITIAL_HABITATS: Habitat[] = [
  {
    id: 'hab_woodland',
    name: 'Mossy Arboretum',
    type: 'woodland',
    description: 'Dappled sunlight, rich canopy humus, and gently rotting fallen timber.',
    themePalette: {
      sky: '#14281d',
      ground: '#064e3b',
      accent: '#34d399',
      foliage: '#059669',
    },
    residentOddkinIds: [],
    lastHarvestTimestamp: Date.now(),
  },
  {
    id: 'hab_workshop',
    name: 'Brass Foundry Bay',
    type: 'workshop',
    description: 'Warm copper conduits, ticking clockwork gears, and soothing forge embers.',
    themePalette: {
      sky: '#1c1917',
      ground: '#44403c',
      accent: '#f59e0b',
      foliage: '#b45309',
    },
    residentOddkinIds: [],
    lastHarvestTimestamp: Date.now(),
  },
  {
    id: 'hab_bog',
    name: 'Bioluminescent Mire',
    type: 'bog',
    description: 'Peaty thermal waters emitting gentle phosphorescent bubbles.',
    themePalette: {
      sky: '#0f172a',
      ground: '#1e293b',
      accent: '#06b6d4',
      foliage: '#0e7490',
    },
    residentOddkinIds: [],
    lastHarvestTimestamp: Date.now(),
  },
  {
    id: 'hab_garden',
    name: 'Prismatic Glasshouse',
    type: 'garden',
    description: 'Terraced moisture beds filtered by crystalline stained panes.',
    themePalette: {
      sky: '#1e1b4b',
      ground: '#312e81',
      accent: '#a855f7',
      foliage: '#7c3aed',
    },
    residentOddkinIds: [],
    lastHarvestTimestamp: Date.now(),
  }
];

/** Merge new process definitions into old saves without losing earned unlocks. */
export function mergeProcesses(saved: Process[] = []): Process[] {
  const known = new Map(saved.map(p => [p.id, p]));
  return ALL_PROCESSES.map(p => ({ ...p, unlocked: p.unlocked || Boolean(known.get(p.id)?.unlocked) }));
}
